name: test-pr

on:
    pull_request:
        # Run on pull requests against the main branch
        branches: [master]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            python-version: [3.8]
            os: [ubuntu-latest]
        env:
          OS: ${{ matrix.os }}
          PYTHON: ${{ matrix.python-version }}

        steps:
        - uses: actions/checkout@main
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@main
          with:
              python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest jupyter nbconvert
            pip install -r requirements.txt
        - name: "Build notebooks"
          run: pytest -v tests/test.py